<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>System.Xml.Serialization</RootNamespace>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <!--NuGet package-->
  <PropertyGroup>
    <Product>XmlSerializerHelper</Product>
    <Description>XmlSerializerHelper serializes and deserializes any .Net object from/to XML.</Description>
    <Version>1.0.0</Version>
    <Authors>Thomas Galliker</Authors>
    <PackageId>XmlSerializerHelper</PackageId>
    <PackageTags>XmlSerializer;XmlSerializerHelper;xml;xmldocument;serializer;helper;serializing;serialize;deserialize</PackageTags>
    <PackageIcon>logo.png</PackageIcon>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/thomasgalliker/XmlSerializerHelper</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/thomasgalliker/XmlSerializerHelper</RepositoryUrl>
    <Company>superdev GmbH</Company>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Copyright>Copyright $([System.DateTime]::Now.ToString(`yyyy`)) © Thomas Galliker</Copyright>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../ReleaseNotes.txt"))</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedAllSources>true</EmbedAllSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="True" PackagePath="\" />
    <None Include="..\LICENSE" Pack="True" PackagePath="\" />
    <None Include="..\logo.png" Pack="True" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
